-- Add all missing notification_type enum values used in the codebase
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'BOOKING_REJECTED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'BOOKING_ACCEPTED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'BOOKING_REFUNDED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'RESCHEDULE_DECLINED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'OFFER_ACCEPTED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'OFFER_DECLINED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_PAST_DUE';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_CANCELLED';
